export   const courses = [
    {
    "id": 1,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 1,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 3,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 4,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 5,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 6,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 7,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 8,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع ری اکت",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },

]