export   const courses = [
    {
    "id": 1,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  React",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش ری اکت با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته ری اکت.",
    "coverImageUrl": "https://www.unicorn.dev/wp-content/uploads/2023/01/react.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 2,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره  جامع  آموزش Zustand",
    "duration": 7,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "متوسط",
    "description": "دوره متمایز آموزش  Zustand با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  Zustand.",
    "coverImageUrl": "https://miro.medium.com/v2/resize:fit:1200/1*y_e4OOiSszPMpyjUD9_BOw.png",
    "numOfChapters": 6,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 150,
    "basePrice": 150000.00
    },
    {
    "id": 3,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع   Graphql",
    "duration": 10,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "پیشرفته",
    "description": "دوره متمایز آموزش Graphql با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته Graphql .",
    "coverImageUrl": "https://everyday.codes/wp-content/uploads/2019/12/og_image.png",
    "numOfChapters": 18,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 4,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  Sass",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش  Sass با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  Sass.",
    "coverImageUrl": "https://miro.medium.com/v2/resize:fit:1200/1*VMM3yJ94Rydzn96y3Xit7Q.jpeg",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 5,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  HTML",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش  HTML با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  HTML.",
    "coverImageUrl": "https://www.cnet.com/a/img/resize/6f59de6f421aca65461420ada94716b37c756c87/hub/2011/01/18/8d118cb0-fdc0-11e2-8c7c-d4ae52e62bcc/HTML5-wow.png?auto=webp&fit=crop&height=675&width=1200",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 6,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  Redux",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "پیشرفته",
    "description": "دوره متمایز آموزش ی Redux با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  Redux.",
    "coverImageUrl": "https://spin.atomicobject.com/wp-content/uploads/redux.jpg",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },
    {
    "id": 7,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  JavaScript",
    "duration": 60,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "پیشرفته",
    "description": "دوره متمایز آموزش  JavaScript با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  JavaScript.",
    "coverImageUrl": "https://allvectorlogo.com/img/2016/04/js-logo.png",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 700,
    "basePrice": 150000.00
    },
    {
    "id": 8,
    "createdAt": "2024-08-02T00:00:00",
    "title": "دوره آموزش جامع  Css",
    "duration": 6,
    "courseCategory": " مهی Front-End11",
    "courseLevel": "مقدماتی",
    "description": "دوره متمایز آموزش  Css با معرفی مفاهیم پایه تا پیاده سازی اپلیکیشن های جذاب | پیاده سازی اپلیکیشن های کاربردی در کنار بررسی مفاهیم پیشرفته  Css.",
    "coverImageUrl": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRVDb6aGsuqtysoxdZP5vZlfdLLSDz-EPD3V4fCcpTQvyClMyaZ",
    "numOfChapters": 10,
    "numOfLectures": 50,
    "averageReviewRating": 5,
    "numOfReviews": 100,
    "basePrice": 150000.00
    },

]